'use client'

import { ChangeEvent, useMemo, useState } from 'react'
import { AlertTriangle, ArrowUpRight, BarChart3, Bell, CheckCircle2, ChevronDown, ClipboardCheck, Clock3, Download, FileText, LayoutDashboard, Menu, PackageCheck, Plus, Search, Settings, ShieldCheck, Upload, UserRound, X, RefreshCw, MapPin, ScanLine } from 'lucide-react'

type Status = 'Action required' | 'Compliant' | 'Under review' | 'Processing'
type Inspection = { id: string; product: string; location: string; date: string; status: Status; score: string; tone: 'danger' | 'success' | 'warning' | 'primary' }

const seed: Inspection[] = [
  { id: 'PKS-2026-0842', product: 'Sunfeast Dark Fantasy', location: 'Khan Market, New Delhi', date: 'Today, 10:42 AM', status: 'Action required', score: '62%', tone: 'danger' },
  { id: 'PKS-2026-0841', product: 'Tata Salt Iodized', location: 'Vasant Vihar, New Delhi', date: 'Today, 09:18 AM', status: 'Compliant', score: '100%', tone: 'success' },
  { id: 'PKS-2026-0839', product: 'Surf Excel Matic', location: 'Lajpat Nagar, New Delhi', date: 'Yesterday, 04:36 PM', status: 'Under review', score: '78%', tone: 'warning' },
  { id: 'PKS-2026-0836', product: 'Parle-G Biscuits', location: 'Karol Bagh, New Delhi', date: 'Yesterday, 01:11 PM', status: 'Compliant', score: '100%', tone: 'success' },
]

const navItems = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'New inspection', icon: Plus }, { label: 'Inspection history', icon: ClipboardCheck }, { label: 'Reports', icon: FileText }]
const angles = ['Front label', 'Back label', 'Left side', 'Right side']

export default function Page() {
  const [active, setActive] = useState('Overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [showUpload, setShowUpload] = useState(false)
  const [files, setFiles] = useState<File[]>([])
  const [product, setProduct] = useState('')
  const [location, setLocation] = useState('')
  const [inspections, setInspections] = useState(seed)
  const [query, setQuery] = useState('')
  const [notice, setNotice] = useState('')

  const filtered = useMemo(() => inspections.filter((item) => `${item.product} ${item.id} ${item.location}`.toLowerCase().includes(query.toLowerCase())), [inspections, query])
  const chooseFiles = (event: ChangeEvent<HTMLInputElement>) => setFiles((current) => [...current, ...Array.from(event.target.files ?? [])].slice(0, 4))
  const startInspection = async () => {
    if (files.length < 4 || !product || !location) return
    const id = `PKS-2026-${String(843 + inspections.length).padStart(4, '0')}`
    setInspections((current) => [{ id, product, location, date: 'Just now', status: 'Processing', score: '—', tone: 'primary' }, ...current])
    setShowUpload(false); setActive('Inspection history'); setNotice(`${id} queued for OCR analysis. Results will appear when processing completes.`)
    try {
      const body = new FormData(); files.forEach((file) => body.append('images', file)); body.append('product', product); body.append('location', location)
      await fetch('/api/inspections', { method: 'POST', body })
    } catch { setNotice('Inspection saved locally in the queue. OCR service is unavailable; retry from history when it is online.') }
    setFiles([]); setProduct(''); setLocation('')
  }

  return <main className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-border bg-sidebar px-5 py-6 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-xl bg-primary text-primary-foreground"><PackageCheck className="size-5" /></div><div><div className="font-serif text-lg font-semibold tracking-tight">PackSahi</div><div className="text-[10px] font-medium uppercase tracking-[0.18em] text-muted-foreground">Field intelligence</div></div></div><button aria-label="Close navigation" className="lg:hidden" onClick={() => setMobileOpen(false)}><X className="size-5" /></button></div>
      <div className="mt-10 flex flex-1 flex-col gap-1"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Workspace</p>{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false); if (label === 'New inspection') setShowUpload(true) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition-colors ${active === label ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-accent hover:text-foreground'}`}><Icon className="size-4" />{label}</button>)}<p className="mt-8 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Manage</p><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-accent hover:text-foreground"><BarChart3 className="size-4" />Analytics</button><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-muted-foreground hover:bg-accent hover:text-foreground"><Settings className="size-4" />Settings</button></div>
      <div className="rounded-xl border border-border bg-background p-3"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-secondary"><UserRound className="size-4 text-muted-foreground" /></div><div className="min-w-0"><p className="truncate text-xs font-semibold">Aarav Mehta</p><p className="truncate text-[11px] text-muted-foreground">Inspector · Delhi Circle</p></div><ChevronDown className="ml-auto size-4 text-muted-foreground" /></div></div>
    </aside>
    <div className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b border-border bg-background/95 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="lg:hidden" onClick={() => setMobileOpen(true)}><Menu className="size-5" /></button><div className="relative hidden md:block"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} aria-label="Search inspections" placeholder="Search inspections..." className="h-9 w-72 rounded-lg border border-input bg-secondary/40 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring" /></div></div><div className="flex items-center gap-4"><button aria-label="Notifications" className="relative text-muted-foreground hover:text-foreground"><Bell className="size-5" /><span className="absolute -right-1 -top-1 size-2 rounded-full bg-destructive ring-2 ring-background" /></button><div className="hidden h-6 w-px bg-border sm:block" /><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-accent text-xs font-semibold text-accent-foreground">AM</div><span className="hidden text-sm font-medium sm:block">Aarav Mehta</span></div></div></header>
      <section className="mx-auto max-w-7xl px-5 py-8 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-primary">Thursday, 30 August 2026</p><h1 className="font-serif text-3xl font-semibold tracking-tight md:text-4xl">Good morning, Aarav.</h1><p className="mt-2 text-sm text-muted-foreground">Here&apos;s the compliance pulse across your inspection zone.</p></div><button onClick={() => setShowUpload(true)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition-transform hover:-translate-y-0.5"><Plus className="size-4" />Start inspection</button></div>
        {notice && <div className="mt-5 flex items-center gap-2 rounded-lg border border-success/30 bg-success/10 px-4 py-3 text-sm text-success"><CheckCircle2 className="size-4" />{notice}<button className="ml-auto" onClick={() => setNotice('')} aria-label="Dismiss notification"><X className="size-4" /></button></div>}
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{ label: 'Inspections this month', value: '128', change: '+14.2%', icon: ClipboardCheck, tone: 'primary' }, { label: 'Compliant packages', value: '94.5%', change: '+2.8%', icon: ShieldCheck, tone: 'success' }, { label: 'Open violations', value: '07', change: '3 high priority', icon: AlertTriangle, tone: 'danger' }, { label: 'Avg. processing time', value: '01:42', change: 'Per package', icon: Clock3, tone: 'warning' }].map(({ label, value, change, icon: Icon, tone }) => <div key={label} className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between"><p className="text-xs font-medium text-muted-foreground">{label}</p><Icon className={`size-4 ${tone === 'danger' ? 'text-destructive' : tone === 'success' ? 'text-success' : tone === 'warning' ? 'text-warning' : 'text-primary'}`} /></div><div className="mt-4 flex items-end justify-between"><p className="text-2xl font-semibold tracking-tight">{value}</p><span className="text-[11px] font-medium text-muted-foreground">{change}</span></div></div>)}</div>
        <div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-semibold">{active === 'Inspection history' ? 'Inspection history' : 'Recent inspections'}</h2><p className="mt-1 text-xs text-muted-foreground">{filtered.length} records matching your workspace</p></div><button onClick={() => setActive('Inspection history')} className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline">View all <ArrowUpRight className="size-3" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-secondary/40 text-[10px] uppercase tracking-[0.12em] text-muted-foreground"><tr><th className="px-5 py-3 font-semibold">Inspection</th><th className="px-3 py-3 font-semibold">Location</th><th className="px-3 py-3 font-semibold">Date</th><th className="px-3 py-3 font-semibold">Status</th><th className="px-5 py-3 text-right font-semibold">Score</th></tr></thead><tbody className="divide-y divide-border">{filtered.map((item) => <tr key={item.id} className="hover:bg-secondary/30"><td className="px-5 py-4"><p className="font-medium">{item.product}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.id}</p></td><td className="px-3 py-4 text-xs text-muted-foreground">{item.location}</td><td className="px-3 py-4 text-xs text-muted-foreground">{item.date}</td><td className="px-3 py-4"><span className={`inline-flex items-center gap-1.5 text-xs font-medium ${item.tone === 'danger' ? 'text-destructive' : item.tone === 'success' ? 'text-success' : item.tone === 'warning' ? 'text-warning' : 'text-primary'}`}><span className={`size-1.5 rounded-full ${item.tone === 'danger' ? 'bg-destructive' : item.tone === 'success' ? 'bg-success' : item.tone === 'warning' ? 'bg-warning' : 'bg-primary'}`} />{item.status}</span></td><td className="px-5 py-4 text-right font-semibold">{item.score}</td></tr>)}</tbody></table></div></div>
          <div className="rounded-xl border border-border bg-primary p-6 text-primary-foreground"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary-foreground/70">Field note</p><h2 className="mt-3 font-serif text-2xl font-semibold leading-tight">Every label tells<br />a story.</h2></div><FileText className="size-5 text-primary-foreground/70" /></div><p className="mt-8 max-w-xs text-sm leading-6 text-primary-foreground/75">Upload clear package images from every angle. PackSahi checks declarations, dates, and MRP against the latest rules.</p><button onClick={() => setShowUpload(true)} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-primary-foreground px-3.5 py-2 text-xs font-semibold text-primary hover:bg-primary-foreground/90"><Upload className="size-3.5" />Upload package</button></div></div>
      </section></div>
    {showUpload && <div className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/30 p-4" role="dialog" aria-modal="true" aria-labelledby="upload-title"><div className="w-full max-w-2xl rounded-2xl border border-border bg-background p-6 shadow-xl"><div className="flex items-start justify-between"><div><h2 id="upload-title" className="font-serif text-2xl font-semibold">Start an inspection</h2><p className="mt-1 text-sm text-muted-foreground">Capture four clear angles for real OCR analysis.</p></div><button aria-label="Close upload dialog" onClick={() => setShowUpload(false)}><X className="size-5 text-muted-foreground" /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-1.5 text-xs font-semibold">Product / brand<input value={product} onChange={(e) => setProduct(e.target.value)} placeholder="e.g. Tata Salt Iodized" className="h-10 rounded-lg border border-input bg-secondary/30 px-3 text-sm font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-1.5 text-xs font-semibold">Inspection location<input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="e.g. Khan Market, New Delhi" className="h-10 rounded-lg border border-input bg-secondary/30 px-3 text-sm font-normal outline-none focus:ring-2 focus:ring-ring" /></label></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{angles.map((label, index) => <label key={label} className={`flex min-h-28 cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border border-dashed ${files[index] ? 'border-success bg-success/5' : 'border-input bg-secondary/30 hover:border-primary'} text-sm transition-colors`}><input type="file" accept="image/jpeg,image/png" className="sr-only" onChange={chooseFiles} /><Upload className={`size-5 ${files[index] ? 'text-success' : 'text-muted-foreground'}`} /><span className="font-medium">{files[index]?.name ?? label}</span><span className="text-[11px] text-muted-foreground">JPG or PNG · max 10MB</span></label>)}</div>{files.length > 0 && <div className="mt-4 flex items-center gap-2 rounded-lg bg-success/10 px-3 py-2 text-xs text-success"><CheckCircle2 className="size-4" />{files.length}/4 images ready for OCR and compliance checks.</div>}<div className="mt-6 flex justify-between gap-3"><span className="flex items-center gap-1.5 text-xs text-muted-foreground"><ScanLine className="size-4" />Evidence-linked analysis</span><div className="flex gap-3"><button onClick={() => setShowUpload(false)} className="rounded-lg px-4 py-2 text-sm font-medium text-muted-foreground hover:bg-secondary">Cancel</button><button disabled={files.length < 4 || !product || !location} onClick={startInspection} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40"><RefreshCw className="size-4" />Run analysis</button></div></div></div></div>}
  </main>
}
